[commands]
use_console = true
use_tty = false
log_console = true
default_op_level = 0
[chat]
format = '<{DISPLAYNAME}> {MESSAGE}'
[pvp]
enabled = true
hurt_animation = true
protect_creative = true
knockback = true
swing = true
[networking.rcon]
enabled = false
max_connections = 0
address = '0.0.0.0:25575'
password = '@djustThyPa$$!'
[networking.rcon.logging]
logged_successfully = true
wrong_password = true
commands = true
quit = true
[networking.proxy]
enabled = false
[networking.proxy.velocity]
enabled = false
secret = ''
[networking.proxy.bungeecord]
enabled = false
[networking.authentication]
enabled = true
connect_timeout = 5000
read_timeout = 5000
prevent_proxy_connections = false
auth_url = ''
prevent_proxy_connection_auth_url = ''
[networking.authentication.player_profile]
allow_banned_players = false
allowed_actions = ['FORCED_NAME_CHANGE', 'USING_BANNED_SKIN']
[networking.authentication.textures]
enabled = true
allowed_url_schemes = ['http', 'https']
allowed_url_domains = ['.minecraft.net', '.mojang.com']
[networking.authentication.textures.types]
skin = true
cape = true
elytra = true
[networking.packet_compression]
enabled = true
threshold = 256
level = 4
[networking.lan_broadcast]
enabled = false
port = 0
[resource_pack]
enabled = false
force = false
url = ''
sha1 = ''
prompt_message = ''
[logging]
enabled = true
env = true
threads = true
color = true
timestamp = true
file = 'latest.log'
level = 'Info'
[world.chunk]
write_in_place = false
linear_version = 'V1'
type = 'anvil'
[world.chunk.compression]
level = 6
algorithm = 'LZ4'
[player_data]
save_player_data = true
save_player_cron_interval = 300
[networking.query]
enabled = false
address = '0.0.0.0:25571'
[server_links]
enabled = true
bug_report = 'https://github.com/Pumpkin-MC/Pumpkin/issues'
support = ''
status = ''
feedback = ''
community = ''
website = ''
forums = ''
news = ''
announcements = ''
[server_links.custom]
Discord = 'https://discord.gg/pumpkin'
[fun]
april_fools = false
